# Use the official Python image from the Docker Hub
FROM python:3.12-bullseye

# Set the working directory in the container
WORKDIR /

# Copy the current directory contents into the container at /app
COPY app/api.py /
COPY agents /agents
COPY utils /utils

COPY requirements.txt /

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENV ELASTIC_HOST='http://chat-rpg-es-internal-http.elastic-system.svc.cluster.local:9200'

# Run app.py when the container launches
CMD ["uvicorn", "api:app", "--host", "0.0.0.0"]